// Type declarations for lucide-react v0.376.0
// This provides simple name exports (Calendar, AlertCircle, etc.) 
// that match the runtime exports, while the actual type declarations
// use Lucide* prefix (LucideCalendar, LucideAlertCircle, etc.)

import type {
  LucideCalendar as Calendar,
  LucideCreditCard as CreditCard,
  LucideBot as Bot,
  LucideAlertCircle as AlertCircle,
  LucideClock as Clock,
  LucideZap as Zap,
  LucideBrain as Brain,
  LucideUserCheck as UserCheck,
  LucideUserX as UserX,
  LucideCalendarX as CalendarX,
  LucideCheckCircle2 as CheckCircle2,
  LucideInfo as Info,
  LucideSparkles as Sparkles,
  LucideSmile as Smile,
  LucideImage as Image,
  LucideFileText as FileText,
  LucideMic2 as Mic2,
  LucideExternalLink as ExternalLink,
  LucideMoreHorizontal as MoreHorizontal,
  LucideMapPin as MapPin,
  LucideMail as Mail,
  LucideStar as Star,
  LucideHeart as Heart,
  LucideShield as Shield,
  LucideSparkle as Sparkle,
  LucideBell as Bell,
  LucideInbox as Inbox,
  LucideClipboardList as ClipboardList,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideSend as Send,
  LucideSmartphone as Smartphone,
  LucideMessageCircle as MessageCircle,
  LucidePhone as Phone,
  LucideUsers as Users,
  LucideCheckCircle as CheckCircle,
  LucideXCircle as XCircle,
  LucideLoader2 as Loader2,
  LucideUser as User,
  LucideUserRound as UserRound,
  LucideUserPlus as UserPlus,
  LucideUserMinus as UserMinus,
  LucideUserCog as UserCog,
  LucideUserRound as UserRound,
  LucideUserCheck as UserCheck,
  LucideUserX as UserX,
  LucideUsers as Users,
  LucideMessageSquare as MessageSquare,
  LucideMessageCircle as MessageCircle,
  LucideMic as Mic,
  LucideMicVocal as Mic2,
  LucidePaperclip as Paperclip,
  LucideSend as Send,
  LucideChevronDown as ChevronDown,
  LucideChevronUp as ChevronUp,
  LucideCheck as Check,
  LucideX as X,
  LucideCalendar as Calendar,
  LucideAlertCircle as AlertCircle,
  LucideClock as Clock,
  LucideZap as Zap,
  LucideBrain as Brain,
  LucideSparkles as Sparkles,
  LucideSparkle as Sparkle,
  LucideSmile as Smile,
  LucideImage as Image,
  LucideFileText as FileText,
  LucideMic2 as Mic2,
  LucideExternalLink as ExternalLink,
  LucideMoreHorizontal as MoreHorizontal,
  LucideMapPin as MapPin,
  LucideMail as Mail,
  LucideStar as Star,
  LucideHeart as Heart,
  LucideShield as Shield,
  LucideSparkle as Sparkle,
  LucideBell as Bell,
  LucideInbox as Inbox,
  LucideClipboardList as ClipboardList,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideMic as Mic,
  LucideMicVocal as Mic2,
  LucidePaperclip as Paperclip,
  LucideSend as Send,
  LucideChevronDown as ChevronDown,
  LucideChevronUp as ChevronUp,
  LucideCheck as Check,
  LucideX as X,
  LucideCalendar as Calendar,
  LucideAlertCircle as AlertCircle,
  LucideClock as Clock,
  LucideZap as Zap,
  LucideBrain as Brain,
  LucideSparkles as Sparkles,
  LucideSparkle as Sparkle,
  LucideSmile as Smile,
  LucideImage as Image,
  LucideFileText as FileText,
  LucideMic2 as Mic2,
  LucideExternalLink as ExternalLink,
  LucideMoreHorizontal as MoreHorizontal,
  LucideMapPin as MapPin,
  LucideMail as Mail,
  LucideStar as Star,
  LucideHeart as Heart,
  LucideShield as Shield,
  LucideSparkle as Sparkle,
  LucideBell as Bell,
  LucideInbox as Inbox,
  LucideClipboardList as ClipboardList,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideMic as Mic,
  LucideMicVocal as Mic2,
  LucidePaperclip as Paperclip,
  LucideSend as Send,
  LucideChevronDown as ChevronDown,
  LucideChevronUp as ChevronUp,
  LucideCheck as Check,
  LucideX as X,
  LucideCalendar as Calendar,
  LucideAlertCircle as AlertCircle,
  LucideClock as Clock,
  LucideZap as Zap,
  LucideBrain as Brain,
  LucideSparkles as Sparkles,
  LucideSparkle as Sparkle,
  LucideSmile as Smile,
  LucideImage as Image,
  LucideFileText as FileText,
  LucideMic2 as Mic2,
  LucideExternalLink as ExternalLink,
  LucideMoreHorizontal as MoreHorizontal,
  LucideMapPin as MapPin,
  LucideMail as Mail,
  LucideStar as Star,
  LucideHeart as Heart,
  LucideShield as Shield,
  LucideSparkle as Sparkle,
  LucideBell as Bell,
  LucideInbox as Inbox,
  LucideClipboardList as ClipboardList,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideAlertTriangle as AlertTriangle,
  LucideWifiOff as WifiOff,
  LucideServer as Server,
  LucideRefreshCw as RefreshCw,
  LucideHome as Home,
  LucideChevronLeft as ChevronLeft,
  LucideShield as Shield,
  LucideLock as Lock,
  LucideSearch as Search,
  LucideMic as Mic,
  LucideMicVocal as Mic2,
  LucidePaperclip as Paperclip,
  LucideSend as Send,
  LucideChevronDown as ChevronDown,
  LucideChevronUp as ChevronUp,
  LucideCheck as Check,
  LucideX as X,
} from "lucide-react";

declare module "lucide-react" {
  export {
    Calendar,
    CreditCard,
    Bot,
    AlertCircle,
    Clock,
    Zap,
    Brain,
    UserCheck,
    UserX,
    CalendarX,
    CheckCircle2,
    Info,
    Sparkles,
    Smile,
    Image,
    FileText,
    Mic2,
    ExternalLink,
    MoreHorizontal,
    MapPin,
    Mail,
    Star,
    Heart,
    Shield,
    Sparkle,
    Bell,
    Inbox,
    ClipboardList,
    AlertTriangle,
    WifiOff,
    Server,
    RefreshCw,
    Home,
    ChevronLeft,
    Shield,
    Lock,
    Search,
    AlertTriangle,
    WifiOff,
    Server,
    RefreshCw,
    Home,
    ChevronLeft,
    Shield,
    Lock,
    Search,
    AlertTriangle,
    WifiOff,
    Server,
    RefreshCw,
    Home,
    ChevronLeft,
    Shield,
    Lock,
    Search,
    Send,
    Smartphone,
    MessageCircle,
    Phone,
    Users,
    CheckCircle,
    XCircle,
    Loader2,
    User,
    UserRound,
    UserPlus,
    UserMinus,
    UserCog,
    UserCheck,
    UserX,
    Users,
    MessageSquare,
    MessageCircle,
    Mic,
    Mic2,
    Paperclip,
    Send,
    ChevronDown,
    ChevronUp,
    Check,
    X,
    Calendar,
    AlertCircle,
    Clock,
    Zap,
    Brain,
    Sparkles,
    Sparkle,
    Smile,
    Image,
    FileText,
    Mic2,
    ExternalLink,
    MoreHorizontal,
    MapPin,
    Mail,
    Star,
    Heart,
    Shield,
    Sparkle,
    Bell,
    Inbox,
    ClipboardList,
    AlertTriangle,
    WifiOff,
    Server,
    RefreshCw,
    Home,
    ChevronLeft,
    Shield,
    Lock,
    Search,
    AlertTriangle,
    WifiOff,
    Server,
    RefreshCw,
    Home,
    ChevronLeft,
    Shield,
    Lock,
    Search,
    Mic,
    Mic2,
    Paperclip,
    Send,
    ChevronDown,
    ChevronUp,
    Check,
    X,
    Calendar,
    AlertCircle,
    Clock,
    Zap,
    Brain,
    Sparkles,
    Sparkle,
    Smile,
    Image,
    FileText,
    Mic2,
    ExternalLink,
    MoreHorizontal,
    MapPin,
    Mail,
    Star,
    Heart,
    Shield,
    Sparkle,
    Bell,
    Inbox,
    ClipboardList,
    AlertTriangle,
    WifiOff,
    Server,
    RefreshCw,
    Home,
    ChevronLeft,
    Shield,
    Lock,
    Search,
    AlertTriangle,
    WifiOff,
    Server,
    RefreshCw,
    Home,
    ChevronLeft,
    Shield,
    Lock,
    Search,
    Mic,
    Mic2,
    Paperclip,
    Send,
    ChevronDown,
    ChevronUp,
    Check,
    X,
    Calendar,
    AlertCircle,
    Clock,
    Zap,
    Brain,
    Sparkles,
    Sparkle,
    Smile,
    Image,
    FileText,
    Mic2,
    ExternalLink,
    MoreHorizontal,
    MapPin,
    Mail,
    Star,
    Heart,
    Shield,
    Sparkle,
    Bell,
    Inbox,
    ClipboardList,
    AlertTriangle,
    WifiOff,
    Server,
    RefreshCw,
    Home,
    ChevronLeft,
    Shield,
    Lock,
    Search,
    AlertTriangle,
    WifiOff,
    Server,
    RefreshCw,
    Home,
    ChevronLeft,
    Shield,
    Lock,
    Search,
    Mic,
    Mic2,
    Paperclip,
    Send,
    ChevronDown,
    ChevronUp,
    Check,
    X,
  };
}